namespace PokemonFieldGuide.Services;

internal static class ChecklistProgressMigrations
{
    private static readonly HashSet<string> Gen2RetiredItems =
    [
        "MAP_LAKE_OF_RAGE_MAGIKARP_HOUSE:event:ETHER:1316",
        "MAP_LAKE_OF_RAGE_MAGIKARP_HOUSE:event:ELIXER:1317",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:SUN_STONE:6864",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:SUN_STONE:6888",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:EVERSTONE:7060",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:EVERSTONE:7084",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:GOLD_BERRY:7256",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:GOLD_BERRY:7280",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:BERRY:7450",
        "MAP_ROUTE_36_NATIONAL_PARK_GATE:event:BERRY:7474",
        "MAP_GOLDENROD_DEPT_STORE_5F:event:TM_RETURN:1646",
        "MAP_GOLDENROD_DEPT_STORE_5F:event:TM_FRUSTRATION:1960",
        "MAP_MOUNT_MOON_SQUARE:hidden:7:7:MOON_STONE",
        "MAP_RADIO_TOWER_1F:event:MASTER_BALL:1636",
        "MAP_RADIO_TOWER_1F:event:EXP_SHARE:1853"
    ];

    private static readonly Dictionary<string, string> CrystalPhoneGifts = new()
    {
        ["MAP_NATIONAL_PARK:event:NUGGET:4988"] = "MAP_NATIONAL_PARK:event:REGISTER_BEVERLY",
        ["MAP_ROUTE_27:event:STAR_PIECE:3047"] = "MAP_ROUTE_27:event:REGISTER_JOSE",
        ["MAP_ROUTE_31:event:BERRY:2866"] = "MAP_ROUTE_31:event:REGISTER_WADE",
        ["MAP_ROUTE_31:event:PSNCUREBERRY:2936"] = "MAP_ROUTE_31:event:REGISTER_WADE",
        ["MAP_ROUTE_31:event:PRZCUREBERRY:3013"] = "MAP_ROUTE_31:event:REGISTER_WADE",
        ["MAP_ROUTE_31:event:BITTER_BERRY:3089"] = "MAP_ROUTE_31:event:REGISTER_WADE",
        ["MAP_ROUTE_34:event:LEAF_STONE:6345"] = "MAP_ROUTE_34:event:REGISTER_GINA",
        ["MAP_ROUTE_36:event:FIRE_STONE:5499"] = "MAP_ROUTE_36:event:REGISTER_ALAN",
        ["MAP_ROUTE_38:event:THUNDERSTONE:2815"] = "MAP_ROUTE_38:event:REGISTER_DANA",
        ["MAP_ROUTE_39:event:NUGGET:1308"] = "MAP_ROUTE_39:event:REGISTER_DEREK",
        ["MAP_ROUTE_42:event:WATER_STONE:2629"] = "MAP_ROUTE_42:event:REGISTER_TULLY",
        ["MAP_ROUTE_43:event:PINK_BOW:5693"] = "MAP_ROUTE_43:event:REGISTER_TIFFANY",
        ["MAP_ROUTE_44:event:ULTRA_BALL:5232"] = "MAP_ROUTE_44:event:REGISTER_WILTON",
        ["MAP_ROUTE_44:event:GREAT_BALL:5321"] = "MAP_ROUTE_44:event:REGISTER_WILTON",
        ["MAP_ROUTE_44:event:POKE_BALL:5409"] = "MAP_ROUTE_44:event:REGISTER_WILTON"
    };

    private static readonly HashSet<string> FrlgRenewableHiddenLocations =
    [
        "MAP_MT_MOON_B1F:46:2", "MAP_MT_MOON_B1F:26:2", "MAP_MT_MOON_B1F:39:34", "MAP_MT_MOON_B1F:24:35", "MAP_MT_MOON_B1F:6:12", "MAP_MT_MOON_B1F:25:34",
        "MAP_THREE_ISLAND_BERRY_FOREST:31:25", "MAP_THREE_ISLAND_BERRY_FOREST:15:15", "MAP_THREE_ISLAND_BERRY_FOREST:25:24", "MAP_THREE_ISLAND_BERRY_FOREST:11:24", "MAP_THREE_ISLAND_BERRY_FOREST:37:18", "MAP_THREE_ISLAND_BERRY_FOREST:14:23", "MAP_THREE_ISLAND_BERRY_FOREST:47:5", "MAP_THREE_ISLAND_BERRY_FOREST:7:30", "MAP_THREE_ISLAND_BERRY_FOREST:16:5", "MAP_THREE_ISLAND_BERRY_FOREST:25:6", "MAP_THREE_ISLAND_BERRY_FOREST:46:32", "MAP_THREE_ISLAND_BERRY_FOREST:43:16", "MAP_THREE_ISLAND_BERRY_FOREST:8:5",
        "MAP_ONE_ISLAND_TREASURE_BEACH:8:20", "MAP_ONE_ISLAND_TREASURE_BEACH:13:27", "MAP_ONE_ISLAND_TREASURE_BEACH:11:31", "MAP_ONE_ISLAND_TREASURE_BEACH:9:34", "MAP_ONE_ISLAND_TREASURE_BEACH:15:22", "MAP_ONE_ISLAND_TREASURE_BEACH:16:33", "MAP_ONE_ISLAND_TREASURE_BEACH:15:29", "MAP_ONE_ISLAND_TREASURE_BEACH:8:27",
        "MAP_THREE_ISLAND_BOND_BRIDGE:44:12", "MAP_THREE_ISLAND_BOND_BRIDGE:33:7",
        "MAP_FIVE_ISLAND_RESORT_GORGEOUS:10:7", "MAP_FIVE_ISLAND_RESORT_GORGEOUS:27:11", "MAP_FIVE_ISLAND_RESORT_GORGEOUS:40:12", "MAP_FIVE_ISLAND_RESORT_GORGEOUS:27:5",
        "MAP_FIVE_ISLAND_MEMORIAL_PILLAR:8:52", "MAP_SIX_ISLAND_OUTCAST_ISLAND:16:23", "MAP_SIX_ISLAND_OUTCAST_ISLAND:6:24", "MAP_SIX_ISLAND_GREEN_PATH:12:9",
        "MAP_SEVEN_ISLAND_TRAINER_TOWER:49:27", "MAP_SEVEN_ISLAND_TRAINER_TOWER:47:30", "MAP_SEVEN_ISLAND_TANOBY_RUINS:33:10", "MAP_SEVEN_ISLAND_TANOBY_RUINS:86:9", "MAP_SEVEN_ISLAND_TANOBY_RUINS:125:5", "MAP_SEVEN_ISLAND_TANOBY_RUINS:8:2",
        "MAP_ROUTE20:23:6", "MAP_ROUTE21_NORTH:17:42", "MAP_FOUR_ISLAND:22:34", "MAP_FOUR_ISLAND:6:21",
        "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:7:3", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:17:5", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:31:4", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:45:3", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:70:3", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:55:2", "MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL:62:5",
        "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:5:30", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:5:6", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:2:57", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:1:24", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:6:53", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:3:15", "MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL:3:39"
    ];

    public static ChecklistProfileData FromVersion2(string packageId, ChecklistProfileData profile)
    {
        if (packageId is "gs" or "crystal") profile.Collected.RemoveWhere(Gen2RetiredItems.Contains);
        if (packageId == "crystal") MigrateCrystal(profile);
        if (packageId == "frlg") profile.Collected.RemoveWhere(IsRemovedFrlgResourceItem);
        return profile;
    }

    private static void MigrateCrystal(ChecklistProfileData profile)
    {
        foreach (var (gift, registration) in CrystalPhoneGifts)
        {
            if (profile.Collected.Remove(gift)) profile.Collected.Add(registration);
        }
        profile.Collected.RemoveWhere(id => id.StartsWith("MAP_BATTLE_TOWER_1F:event:BATTLE_TOWER_REWARD:", StringComparison.Ordinal));
    }

    private static bool IsRemovedFrlgResourceItem(string id)
    {
        if (id.StartsWith("MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE:event:ITEM_", StringComparison.Ordinal)
            || id is "MAP_ROUTE12_FISHING_HOUSE:event:2751" or "MAP_SIX_ISLAND_WATER_PATH_HOUSE1:event:2024") return true;
        var parts = id.Split(':');
        return parts.Length == 4 && parts[1] == "hidden" && FrlgRenewableHiddenLocations.Contains($"{parts[0]}:{parts[2]}:{parts[3]}");
    }
}
