import fs from 'node:fs';
import path from 'node:path';

import { addScriptedItems } from '../gen4/scripted-items.mjs';

const rewards = [
  ['MAP_JUBLIFE','ITEM_FASHION_CASE'], ['MAP_JUBLIFE','ITEM_COUPON_1'], ['MAP_JUBLIFE','ITEM_COUPON_2'], ['MAP_JUBLIFE','ITEM_COUPON_3'],
  ['MAP_JUBLIFE_CONDOMINIUMS_1F','ITEM_QUICK_CLAW'], ['MAP_JUBLIFE_CONDOMINIUMS_4F','ITEM_FOCUS_BAND'],
  ['MAP_JUBLIFE_TRAINER_SCHOOL','ITEM_TOWN_MAP'], ['MAP_JUBLIFE_TRAINER_SCHOOL','ITEM_TM10'],
  ['MAP_CANALAVE_GYM','ITEM_TM91'], ['MAP_CANALAVE_SOUTHEAST_HOUSE','ITEM_TM48'],
  ['MAP_OREBURGH','ITEM_SUPER_POTION'], ['MAP_OREBURGH_GYM','ITEM_TM76'],
  ['MAP_OREBURGH_NORTHWEST_HOUSE_2F','ITEM_DUSK_BALL'], ['MAP_OREBURGH_NORTHWEST_HOUSE_3F','ITEM_HARD_STONE'],
  ['MAP_OREBURGH_NORTH_HOUSE_2F','ITEM_HEAL_BALL'], ['MAP_OREBURGH_EAST_HOUSE_2F','ITEM_GREAT_BALL'],
  ['MAP_ETERNA','ITEM_HM01'], ['MAP_ETERNA_GYM','ITEM_TM86'], ['MAP_ETERNA_BIKE_SHOP','ITEM_BICYCLE'],
  ['MAP_ETERNA_CONDOMINIUMS_2F','ITEM_TM67'], ['MAP_ETERNA_CONDOMINIUMS_4F','ITEM_TM04'],
  ['MAP_ETERNA_ROUTE_206_GATEHOUSE','ITEM_EXP__SHARE'], ['MAP_ETERNA_OAK_HOUSE','ITEM_UPGRADE'],
  ['MAP_ETERNA_UNDERGROUND_MAN_HOUSE','ITEM_EXPLORER_KIT'], ['MAP_HEARTHOME_GYM_LEADER_ROOM','ITEM_TM65'],
  ['MAP_HEARTHOME_SOUTHEAST_HOUSE_2F','ITEM_SHELL_BELL'], ['MAP_HEARTHOME_POKEMON_FAN_CLUB','ITEM_POFFIN_CASE'],
  ['MAP_PASTORIA_GYM','ITEM_TM55'], ['MAP_PASTORIA_WEST_HOUSE','ITEM_MACHO_BRACE'],
  ['MAP_PASTORIA_SCARF_GUY_HOUSE','ITEM_RED_SCARF'], ['MAP_PASTORIA_SCARF_GUY_HOUSE','ITEM_BLUE_SCARF'],
  ['MAP_PASTORIA_SCARF_GUY_HOUSE','ITEM_PINK_SCARF'], ['MAP_PASTORIA_SCARF_GUY_HOUSE','ITEM_GREEN_SCARF'],
  ['MAP_PASTORIA_SCARF_GUY_HOUSE','ITEM_YELLOW_SCARF'], ['MAP_VEILSTONE','ITEM_TM63'],
  ['MAP_VEILSTONE_GYM','ITEM_TM60'], ['MAP_VEILSTONE_GAME_CORNER','ITEM_TM64'],
  ['MAP_VEILSTONE_DEPARTMENT_STORE_5F','ITEM_STICKY_BARB'], ['MAP_VEILSTONE_SOUTH_HOUSE','ITEM_COIN_CASE'],
  ['MAP_SUNYSHORE','ITEM_HM07'], ['MAP_SUNYSHORE_GYM_ROOM_3','ITEM_TM57'], ['MAP_SNOWPOINT_GYM','ITEM_TM72'],
  ['MAP_FIGHT_AREA','ITEM_SUPER_ROD'], ['MAP_FIGHT_AREA_POKEMART','ITEM_SCOPE_LENS'],
  ['MAP_FIGHT_AREA_BATTLE_PARK_GATEHOUSE','ITEM_POINT_CARD'], ['MAP_FUEGO_IRONWORKS_INTERIOR','ITEM_FIRE_STONE'],
  ['MAP_FLOAROMA_MEADOW','ITEM_WORKS_KEY'], ['MAP_FLOAROMA_MEADOW','ITEM_HONEY',10],
  ['MAP_OREBURGH_GATE_1F','ITEM_HM06'], ['MAP_VEILSTONE_GALACTIC_HEADQUARTERS_4F_1','ITEM_MASTER_BALL'],
  ['MAP_VALOR_LAKEFRONT','ITEM_SECRETPOTION'], ['MAP_VALOR_LAKEFRONT_GRAND_LAKE_EAST_ROOM','ITEM_LAVA_COOKIE'],
  ['MAP_ROUTE_201','ITEM_POTION'], ['MAP_ROUTE_202','ITEM_POKE_BALL',5], ['MAP_ROUTE_204_NORTH','ITEM_TM78'],
  ['MAP_ROUTE_207','ITEM_VS__SEEKER'], ['MAP_ROUTE_208','ITEM_ODD_KEYSTONE'], ['MAP_ROUTE_209','ITEM_GOOD_ROD'],
  ['MAP_ROUTE_209_LOST_TOWER_5F','ITEM_HM04'], ['MAP_ROUTE_209_LOST_TOWER_5F','ITEM_CLEANSE_TAG'],
  ['MAP_ROUTE_210_SOUTH','ITEM_OLD_CHARM'], ['MAP_ROUTE_210_SOUTH','ITEM_TM51'], ['MAP_ROUTE_211_EAST','ITEM_TM77'],
  ['MAP_ROUTE_212_POKEMON_MANSION_WEST_ROOMS','ITEM_SOOTHE_BELL'], ['MAP_ROUTE_213_GRAND_LAKE_WEST_ROOM','ITEM_TM92'],
  ['MAP_ROUTE_215','ITEM_TM66'], ['MAP_ROUTE_217_SOUTH_HOUSE','ITEM_ICICLE_PLATE'],
  ['MAP_ROUTE_217_NORTH_HOUSE','ITEM_SPELL_TAG'], ['MAP_ROUTE_218_JUBLIFE_GATEHOUSE','ITEM_OLD_ROD'],
  ['MAP_ROUTE_222','ITEM_TM56'], ['MAP_ROUTE_229','ITEM_NUGGET',2],
  ['MAP_TWINLEAF_RIVAL_HOUSE_1F','ITEM_JOURNAL'], ['MAP_TWINLEAF_RIVAL_HOUSE_1F','ITEM_PARCEL'],
  ['MAP_SANDGEM_ROWANS_LAB','ITEM_POKE_RADAR'], ['MAP_FLOAROMA_FLOWER_SHOP','ITEM_SPRAYDUCK'],
  ['MAP_FLOAROMA_MIDDLE_HOUSE','ITEM_TM88'], ['MAP_SOLACEON_SEAL_HOUSE','ITEM_SEAL_CASE'],
  ['MAP_CELESTIC_SHOP','ITEM_CHOICE_SPECS'], ['MAP_CELESTIC_SHOP','ITEM_BLACKGLASSES'], ['MAP_CELESTIC_SHOP','ITEM_WISE_GLASSES'],
  ['MAP_CELESTIC_RUINS','ITEM_HM03'], ['MAP_SURVIVAL_AREA_SOUTH_HOUSE','ITEM_TM42'],
  ['MAP_ROUTE_225_HOUSE','ITEM_FRESH_WATER'], ['MAP_GREAT_MARSH_AREA_6','ITEM_HM05'],
  ['MAP_IRON_ISLAND_HOUSE','ITEM_METAL_COAT']
].map(([areaId, itemId, quantity]) => ({ areaId, itemId, quantity }));

export function addDpScriptedItems(source, areas, headers, items, itemNumbers) {
  addScriptedItems(areas, items, rewards, reward => {
    const scriptId = headers.get(reward.areaId)?.scriptId;
    const number = itemNumbers.get(reward.itemId);
    const file = Number.isInteger(scriptId)
      ? path.join(source, `files/fielddata/script/scr_seq_release/narc_${String(scriptId).padStart(4, '0')}.bin`)
      : null;
    if (!file || !fs.existsSync(file) || !Number.isInteger(number)) {
      throw new Error(`Diamond/Pearl source script for ${reward.areaId} cannot resolve ${reward.itemId}.`);
    }
    const needle = Buffer.alloc(2); needle.writeUInt16LE(number);
    if (!fs.readFileSync(file).includes(needle)) {
      throw new Error(`Diamond/Pearl source script for ${reward.areaId} does not reference ${reward.itemId}.`);
    }
  });
}

export const dpScriptedRewardCount = rewards.length;
