import fs from 'node:fs';
import path from 'node:path';

import { addScriptedItems } from '../gen4/scripted-items.mjs';

const rewards = [
  ['MAP_HEADER_CANALAVE_CITY_GYM','ITEM_TM91'], ['MAP_HEADER_CANALAVE_CITY_SOUTHEAST_HOUSE','ITEM_TM48'],
  ['MAP_HEADER_CELESTIC_TOWN_CAVE','ITEM_HM03'], ['MAP_HEADER_CELESTIC_TOWN_NORTHWEST_HOUSE','ITEM_CHOICE_SPECS'],
  ['MAP_HEADER_CELESTIC_TOWN_NORTHWEST_HOUSE','ITEM_BLACKGLASSES'], ['MAP_HEADER_CELESTIC_TOWN_NORTHWEST_HOUSE','ITEM_WISE_GLASSES'],
  ['MAP_HEADER_CYCLE_SHOP','ITEM_BICYCLE'], ['MAP_HEADER_ETERNA_CITY','ITEM_HM01'],
  ['MAP_HEADER_ETERNA_CITY_CONDOMINIUMS_2F','ITEM_TM67'], ['MAP_HEADER_ETERNA_CITY_GYM','ITEM_TM86'],
  ['MAP_HEADER_ETERNA_CITY_SOUTH_HOUSE','ITEM_UPGRADE'], ['MAP_HEADER_ETERNA_CITY_UNDERGROUND_MAN_HOUSE','ITEM_EXPLORER_KIT'],
  ['MAP_HEADER_ETERNA_FOREST','ITEM_SOOTHE_BELL'], ['MAP_HEADER_FIGHT_AREA','ITEM_SUPER_ROD'],
  ['MAP_HEADER_FIGHT_AREA_MART','ITEM_SCOPE_LENS'], ['MAP_HEADER_FLOAROMA_MEADOW','ITEM_WORKS_KEY'],
  ['MAP_HEADER_FLOAROMA_MEADOW','ITEM_HONEY',10], ['MAP_HEADER_FLOAROMA_TOWN','ITEM_GRACIDEA'],
  ['MAP_HEADER_FLOAROMA_TOWN_MIDDLE_HOUSE','ITEM_TM88'], ['MAP_HEADER_FLOWER_SHOP','ITEM_SPRAYDUCK'],
  ['MAP_HEADER_FUEGO_IRONWORKS_BUILDING','ITEM_STAR_PIECE'], ['MAP_HEADER_GALACTIC_HQ_4F','ITEM_MASTER_BALL'],
  ['MAP_HEADER_GAME_CORNER','ITEM_TM64'], ['MAP_HEADER_GRAND_LAKE_ROUTE_213_NORTHWEST_HOUSE','ITEM_TM92'],
  ['MAP_HEADER_GRAND_LAKE_VALOR_LAKEFRONT_EAST_HOUSE','ITEM_WHITE_FLUTE'], ['MAP_HEADER_HEARTHOME_CITY_GYM_LEADER_ROOM','ITEM_TM65'],
  ['MAP_HEADER_HEARTHOME_CITY_POKEMON_FAN_CLUB','ITEM_POFFIN_CASE'], ['MAP_HEADER_HEARTHOME_CITY_SOUTHEAST_HOUSE_2F','ITEM_SHELL_BELL'],
  ['MAP_HEADER_IRON_ISLAND','ITEM_HM04'], ['MAP_HEADER_IRON_ISLAND_HOUSE','ITEM_METAL_COAT'],
  ['MAP_HEADER_JUBILIFE_CITY','ITEM_VS_RECORDER'], ['MAP_HEADER_JUBILIFE_CITY','ITEM_FASHION_CASE'],
  ['MAP_HEADER_JUBILIFE_CITY','ITEM_COUPON_1'], ['MAP_HEADER_JUBILIFE_CITY','ITEM_COUPON_2'], ['MAP_HEADER_JUBILIFE_CITY','ITEM_COUPON_3'],
  ['MAP_HEADER_JUBILIFE_CITY_CONDOMINIUMS_1F','ITEM_QUICK_CLAW'], ['MAP_HEADER_MT_CORONET_2F','ITEM_BLACK_FLUTE'],
  ['MAP_HEADER_OREBURGH_CITY','ITEM_SUPER_POTION'], ['MAP_HEADER_OREBURGH_CITY_EAST_HOUSE_2F','ITEM_GREAT_BALL'],
  ['MAP_HEADER_OREBURGH_CITY_GYM','ITEM_TM76'], ['MAP_HEADER_OREBURGH_CITY_NORTH_HOUSE_2F','ITEM_HEAL_BALL'],
  ['MAP_HEADER_OREBURGH_CITY_NORTHWEST_HOUSE_2F','ITEM_DUSK_BALL'], ['MAP_HEADER_OREBURGH_GATE_1F','ITEM_HM06'],
  ['MAP_HEADER_OREBURGH_MINE_B1F','ITEM_FLAME_PLATE'], ['MAP_HEADER_PASTORIA_CITY_GYM','ITEM_TM55'],
  ['MAP_HEADER_PASTORIA_CITY_MIDDLE_HOUSE','ITEM_MACHO_BRACE'], ['MAP_HEADER_PASTORIA_CITY_NORTHEAST_HOUSE','ITEM_RED_SCARF'],
  ['MAP_HEADER_PASTORIA_CITY_NORTHEAST_HOUSE','ITEM_BLUE_SCARF'], ['MAP_HEADER_PASTORIA_CITY_NORTHEAST_HOUSE','ITEM_PINK_SCARF'],
  ['MAP_HEADER_PASTORIA_CITY_NORTHEAST_HOUSE','ITEM_GREEN_SCARF'], ['MAP_HEADER_PASTORIA_CITY_NORTHEAST_HOUSE','ITEM_YELLOW_SCARF'],
  ['MAP_HEADER_POKEMON_MANSION_MAIDS_ROOM','ITEM_SOOTHE_BELL'], ['MAP_HEADER_ROUTE_201','ITEM_POTION'],
  ['MAP_HEADER_ROUTE_202','ITEM_POKE_BALL',5], ['MAP_HEADER_ROUTE_204_NORTH','ITEM_TM78'],
  ['MAP_HEADER_ROUTE_206_CYCLING_ROAD_NORTH_GATE','ITEM_EXP_SHARE'], ['MAP_HEADER_ROUTE_207','ITEM_VS_SEEKER'],
  ['MAP_HEADER_ROUTE_208','ITEM_ODD_KEYSTONE'], ['MAP_HEADER_ROUTE_209','ITEM_GOOD_ROD'],
  ['MAP_HEADER_ROUTE_209_LOST_TOWER_5F','ITEM_SPELL_TAG'], ['MAP_HEADER_ROUTE_209_LOST_TOWER_5F','ITEM_CLEANSE_TAG'],
  ['MAP_HEADER_ROUTE_210_SOUTH','ITEM_OLD_CHARM'], ['MAP_HEADER_ROUTE_210_SOUTH','ITEM_TM51'],
  ['MAP_HEADER_ROUTE_211_EAST','ITEM_TM77'], ['MAP_HEADER_ROUTE_215','ITEM_TM66'],
  ['MAP_HEADER_ROUTE_217_NORTHEAST_HOUSE','ITEM_SPELL_TAG'], ['MAP_HEADER_ROUTE_217_WEST_HOUSE','ITEM_ICICLE_PLATE'],
  ['MAP_HEADER_ROUTE_218_GATE_TO_JUBILIFE_CITY','ITEM_OLD_ROD'], ['MAP_HEADER_ROUTE_222','ITEM_TM56'],
  ['MAP_HEADER_ROUTE_225_HOUSE','ITEM_FRESH_WATER'], ['MAP_HEADER_ROUTE_229','ITEM_NUGGET',2],
  ['MAP_HEADER_SANDGEM_TOWN','ITEM_TM27'], ['MAP_HEADER_SANDGEM_TOWN_POKEMON_RESEARCH_LAB','ITEM_POKE_RADAR'],
  ['MAP_HEADER_SNOWPOINT_CITY_GYM','ITEM_TM72'], ['MAP_HEADER_SOLACEON_RUINS_ROOM_2','ITEM_GREEN_SHARD'],
  ['MAP_HEADER_SOLACEON_TOWN_EAST_HOUSE','ITEM_SEAL_CASE'], ['MAP_HEADER_SUNYSHORE_CITY','ITEM_HM07'],
  ['MAP_HEADER_SUNYSHORE_CITY_GYM_ROOM_3','ITEM_TM57'], ['MAP_HEADER_SURVIVAL_AREA_SOUTH_HOUSE','ITEM_TM42'],
  ['MAP_HEADER_TRAINERS_SCHOOL','ITEM_TOWN_MAP'], ['MAP_HEADER_TRAINERS_SCHOOL','ITEM_POTION'],
  ['MAP_HEADER_TWINLEAF_TOWN_PLAYER_HOUSE_1F','ITEM_JOURNAL'], ['MAP_HEADER_TWINLEAF_TOWN_PLAYER_HOUSE_1F','ITEM_PARCEL'],
  ['MAP_HEADER_VALOR_LAKEFRONT','ITEM_SECRETPOTION'], ['MAP_HEADER_VEILSTONE_CITY','ITEM_TM63'],
  ['MAP_HEADER_VEILSTONE_CITY_GYM','ITEM_TM60'], ['MAP_HEADER_VEILSTONE_CITY_SOUTHEAST_HOUSE','ITEM_COIN_CASE'],
  ['MAP_HEADER_VEILSTONE_STORE_5F','ITEM_STICKY_BARB']
].map(([areaId, itemId, quantity]) => ({ areaId, itemId, quantity }));

export function addPlatinumScriptedItems(source, areas, headers, items) {
  addScriptedItems(areas, items, rewards, reward => {
    const archive = headers.get(reward.areaId)?.scriptArchive;
    const file = archive && path.join(source, 'res/field/scripts', `${archive}.s`);
    if (!file || !fs.existsSync(file) || !fs.readFileSync(file, 'utf8').includes(reward.itemId)) {
      throw new Error(`Platinum source script for ${reward.areaId} does not reference ${reward.itemId}.`);
    }
  });
}

export const platinumScriptedRewardCount = rewards.length;
